### ISSUE TITLE
Better error message for implicitly returned anonymous classes

### ISSUE THREAD

**Issue by wcjohnson** [lightscript/lightscript#10]
This code gives a parse error at `extends`:
```javascript
g() ->
  class extends Base:
    constructor() -> super()
```
whereas this does not:
```javascript
g() ->
  class Subclass extends Base:
    constructor() -> super()
```
nor does this:
```javascript
g() ->
  return class extends Base:
    constructor() -> super()
```

I traced this back into babylon, and when a class declaration appears outside of expression context, it requires a name. Since babylon isn't aware of the implicit return transformation, it doesn't know the first code example is actually an expression, and it chokes.

This code style is relevant, I think. To name one example from the ecosystem, higher-order components for React use this pattern of generating and returning anonymous classes.

My proposal:

Let's allow `babylon-lightscript` to create anonymous-class parse tree nodes even at statement level, then in the AST transform, throw an error if someone puts an anonymous class node outside of expr context.

**Comment by rattrayalex** [comment]
Interesting. I'm pretty fine requiring an explicit `return` or a name for the class – I'd rather encourage named classes where possible. 

Throwing the no-anon error at the plugin level sounds potentially tricky... I'd rather avoid that if possible. 

Okay to close this for now?

**Comment by wcjohnson** [comment]
Yeah, I think just requiring the return is fine, messing with the parser just for this is probably too little benefit for the effort. Perhaps should be documented, but OK to close.

**Comment by rattrayalex** [comment]
Yeah agreed it should ideally be documented... I can't think of a good place other than perhaps just this issue. Seems too trivial to add to the official docs... thoughts?

**Comment by wcjohnson** [comment]
Maybe a catch-all section at the bottom for "gotchas" or something? We've run across a couple of minor things like this already if I remember correctly. No doubt a few will accumulate.

The reason I say that is I had absolutely no idea what was going on here until I dug into the parser myself and found out -- which most people won't do. The message isn't "you can't return an anonymous class implcitly", it's just "unexpected token."

**Comment by wcjohnson** [comment]
You could add it to "known ambiguities" (though it's not an ambiguity, per se) or retitle that section to "gotchas" or "potential pitfalls" or something? Not sure, but I stepped on it pretty quickly myself, so I think it's worth writing down.
