### ISSUE TITLE
`babel-plugin-lightscript`: auto-const code

### ISSUE THREAD

**Issue by wcjohnson** [lightscript/lightscript#11]
https://github.com/lightscript/babel-plugin-lightscript/blob/master/src/index.js#L916

At first I thought this was just dead code with the new `for` changes, but now I think it may be a bug.

If I'm reading this correctly, it's flatly changing the declaration to `const` even if you write something like `let` or `var`. (This would not break the new `for..in` loops because their node type is `ForIn(Array|Object)Statement`)

Possibly responsible for a couple strange things we were talking about earlier, like how some of the example code had "now" instead of "const" but was still running correctly.

I didn't want to contaminate any outstanding PRs with it, but I think this is a target for removal.

**Comment by rattrayalex** [comment]
Ah, yes, that should have been removed earlier. Good catch.

**Comment by rattrayalex** [comment]
I can take care of this tomorrow probably
