### ISSUE TITLE
Support Async Generators and `for await (...) of`

### ISSUE THREAD

**Issue by mikeyhew** [lightscript/lightscript#15]
The [Async Iteration proposal](https://github.com/tc39/proposal-async-iteration) is in stage three, and is [being implemented in v8 right now](https://bugs.chromium.org/p/v8/issues/detail?id=5855). It includes a new `Symbol.asyncIterator` protocol, async generator functions with `async function*`, and a new `for await (...) of` loop for asynchronous iteration.

You can test it out on Chrome Canary with `--js-flags='--harmony-async-iteration'`, or with `babel-plugin-transform-async-generator-functions`.

So can it be supported in Lighscript? The syntax for async generator functions in Lightscript would presumably be `-/*>` and `=/*>`. `for await ... of` would be pretty similar to the javascript, and to Lightscript's `for ... of` loop. `Symbol.asyncIterator` isn't a language feature so we don't need to worry about it.

**Comment by rattrayalex** [comment]
Sure! Any interest in building it? :wink: happy to help & show you the ropes!

**Comment by mikeyhew** [comment]
Sure, I'd be happy to. I have exams next week, but should have some time after Easter. I'll ping you on gitter?

**Comment by rattrayalex** [comment]
Sounds great!

**Comment by rattrayalex** [comment]
Merged
