### ISSUE TITLE
`babylon-lightscript`: Incorrect ASI for `new`

### ISSUE THREAD

**Issue by wcjohnson** [lightscript/lightscript#16]
## Input
```js
f() ->
  throw new Error
  
  (() -> x)
```

## Output
```js
function f() {
  throw new Error(function() {
    return x;
  });
}
```

## Expected
```js
function f() {
  throw new Error();

  function() {
    return x;
  };
}
```

## Resolution
The ASI rules for LightScript specify that if the opening paren doesn't fall on the same line of a function call, a semicolon is inserted. That rule should probably apply in situations like this as well.

**Comment by rattrayalex** [comment]
Ah, I think `new` expressions have a different parsing path. Good catch, thanks!

**Comment by rattrayalex** [comment]
Fixed in https://github.com/lightscript/babylon-lightscript/pull/11
