### ISSUE TITLE
[plugin] False positive variable shadowing

### ISSUE THREAD

**Issue by wcjohnson** [lightscript/lightscript#18]
```js
f = (x) ->
  x.stuff()

describe('suite', ->
  it('test', ->
    x = somethingElse()
  )
)
```
yields:
```
unknown: `x` is shadowed from a higher scope. If you want to reassign the variable, use `now x = ...`. If you want to declare a new shadowed `const` variable, you must use `const x = ...` explicitly.
  4 | describe('suite', ->
  5 |   it('test', ->
> 6 |     x = somethingElse()
    |     ^
  7 |   )
  8 | )
```
which is not correct: the scope of the interior function does not conflict with the scope of f.

Even stranger, if the function is declared as named instead of anonymous:
```js
f(x) ->
  x.stuff()

describe('suite', ->
  it('test', ->
    x = somethingElse()
  )
)
```
it compiles correctly!
```js
function f(x) {
  return x.stuff();
}

describe("suite", function() {
  return it("test", function() {
    const x = somethingElse();
    return x;
  });
});
```

**Comment by rattrayalex** [comment]
Interesting. Thanks for reporting, I'll look into this.

**Comment by haltcase** [comment]
Just curious, if you remove the `x` assignment and just put a noop or something, what does it actually compile to? Does it put the `describe` within `f()`?

**Comment by wcjohnson** [comment]
@citycide Not sure exactly what you mean, but if I resolve the conflict by renaming a var it compiles as I would expect:

```js
f = (y) ->
  y.stuff()

describe('suite', ->
  it('test', ->
    x = somethingElse()
  )
)
```
goes to
```
const f = function(y) {
  return y.stuff();
};

describe("suite", function() {
  return it("test", function() {
    const x = somethingElse();
    return x;
  });
});
```

So I don't think it's an actual parsing/nesting error.

EDIT: This (which is probably what you meant) also works as expected:
```js
f = (x) ->
  x.stuff()

describe('suite', ->
  it('test', ->
    doesNothing()
  )
)
```
```js
const f = function(x) {
  return x.stuff();
};

describe("suite", function() {
  return it("test", function() {
    return doesNothing();
  });
});
```

**Comment by wcjohnson** [comment]
@rattrayalex 

Did some digging on this. Commenting this out:
https://github.com/lightscript/babel-plugin-lightscript/blob/master/src/index.js#L1082

fixes the issue, but also causes issues in other fixtures. 

I think the fix here might be to only run that code on nodes that are actually FunctionDeclarations, rather than on all Function nodes. Will see if I can make that work.

**Comment by rattrayalex** [comment]
That sounds like a good path of pursuit

**Comment by wcjohnson** [comment]
Yeah, that was it.

**Comment by rattrayalex** [comment]
Fixed in https://github.com/lightscript/babel-plugin-lightscript/pull/15
