### ISSUE TITLE
[parser] 0.5.0: newline after `else`

### ISSUE THREAD

**Issue by wcjohnson** [lightscript/lightscript#20]
According to the notes for 0.5.0, newlines after `else` are now illegal. However, this still parses:
```js
if a:
  b
else
  if b: c
```
I think if newlines after else are going to be disallowed, this should definitely be a parse error.

**Comment by rattrayalex** [comment]
Agreed – I actually meant to do that.

**Comment by rattrayalex** [comment]
Would you like to do that or shall I?

**Comment by wcjohnson** [comment]
I haven't had a chance to process the new code yet, so it would probably take me a while to get up to speed -- if it's a quick fix for you, I'd say just change it on your end.

**Comment by rattrayalex** [comment]
Fixed in https://github.com/lightscript/babylon-lightscript/commit/80e92207516941bf41dc879d2caeb95151518570
