### ISSUE TITLE
[parser] 0.5.0: if expr/stmt inconsistency

### ISSUE THREAD

**Issue by wcjohnson** [lightscript/lightscript#21]
Now that the syntaxes are unified, these should both compile, right?
```js
if(true) 1
```
```js
x = if(true) 1
```

First works, second one yields:
```
  index › lightscript/if expression/vanilla
  Error: lightscript/if-expression/vanilla/actual.js: Unexpected token, expected : (1:13)
    Parser.pp$5.raise (src/parser/location.js:15:15)
    Parser.pp.unexpected (src/parser/util.js:111:8)
    Parser.pp.expect (src/parser/util.js:95:33)
    Parser.pp$7.parseWhiteBlock (src/plugins/lightscript.js:241:10)
    Parser.pp$7.parseIf (src/plugins/lightscript.js:456:14)
    Parser.pp$7.parseIfExpression (src/plugins/lightscript.js:507:15)
    Parser.pp$3.parseExprAtom (src/parser/expression.js:687:21)
...
```

**Comment by rattrayalex** [comment]
Huh, that's unfortunate. Not immediately sure why. Can confirm with eg; `x = if (1) 'hi'`

**Comment by wcjohnson** [comment]
The culprit is here:
https://github.com/lightscript/babylon-lightscript/blob/lightscript/src/plugins/lightscript.js#L178

Because there isn't a curly brace, `parseIf` is calling for whiteblock parsing even though that isn't technically whiteblock syntax; whiteblock parsing demands a colon there; there isn't one.

Possible fixes:
- Make the colon there optional; if not present, assume oneline
- Check for the colon in `parseIf` and add an `optionalColon` arg to parseWhiteBlock
- Third special case in `parseIf` for no colon or brace
- ???

**Comment by wcjohnson** [comment]
Actually I think you already solved this problem in `parseIfAlternate`:

This just needs to be copied upward to `ParseIf`:
```js
    if (isExpression) {
      if (this.match(tt.braceL)) {
        return this.parseBlock(false);
      } else if (!this.match(tt.colon)) {
        return this.parseMaybeAssign();
      } else {
        return this.parseWhiteBlock(false, true);
      }
    }
```
