### ISSUE TITLE
[plugin] Implicit returns and assignment expressions

### ISSUE THREAD

**Issue by wcjohnson** [lightscript/lightscript#26]
## Problem
According to the ECMAScript standard, an assignment expression evaluates to its rvalue:

http://www.ecma-international.org/ecma-262/5.1/#sec-11.13.1

However, LSC compiles as follows:
```
f(k,v) ->
  this[k] = v
```
```
function f(k, v) {
  this[k] = v;
  return this[k];
}
```

So basically, LSC is implicitly returning the lvalue of the assignment expression instead of the rvalue. This has semantic consequences. For instance, if `this[k]` has a getter, the function will return the result of `this[k]`'s getter instead of the value `v`. If the getter returns a value different from `v` then a user expecting Ecmascript assignment semantics will be confused by the return value of that function.

## Resolution
We should consider producing:
```
function f(k, v) {
  return (this[k] = v);
}
```
instead, which would allow the JS engine to enforce the expression semantics correctly.

**Comment by rattrayalex** [comment]
Agreed. I can't recall why it was done this way originally; I think it may have had to do with implicit return of VariableDeclarations, but I don't think that applies at this point.
