### ISSUE TITLE
[docs] Various nits/updates

### ISSUE THREAD

**Issue by wcjohnson** [lightscript/lightscript#27]
- [x] In `Whitespace > When does an indent end?` the docs advocate a type of `else` indentation which no longer works due to the changes made to significant whitespace. An `else` must match the indent level of the corresponding `if` when the `if` uses whiteblock syntax.

- [x] In `Loops > Iterating over Objects` the documentation regarding the `hasOwnProperty()` check is out of date.

- [ ] In `Automatic Semicolon Insertion` we should probably document that the open paren for named arrow function arguments must appear on the same line as the function name.

- [ ] In `No newlines after if, while, switch, with` we should probably mention the new rules surrounding `else`

**Comment by rattrayalex** [comment]
Nice! Great list, I'll try to add those updates soon

**Comment by rattrayalex** [comment]
1. Added in https://github.com/lightscript/lightscript.org/commit/f120c42da46b7d6dea4bdeb2941cdb689f073de0
2. @citycide added in https://github.com/lightscript/lightscript.org/commit/5bd3d5f0ca48c879bf4f9edcef7c26aea0724577
3. That section intends to document changes to JS-proper, and named arrow functions are a new feature. So it should be documented in that section, if anywhere, but I'd rather the docs not be that pedantic for now...
4. PR up in https://github.com/lightscript/lightscript.org/pull/4

**Comment by rattrayalex** [comment]
Closing as done, lemme know if you think anything should be further clarified?
