### ISSUE TITLE
[plugin] Automatic `super` insertion and nested calls

### ISSUE THREAD

**Issue by wcjohnson** [lightscript/lightscript#33]
```js
class c extends s:
  constructor() ->
    f() -> supr("bad")    
```
```js
class c extends s {
  constructor(..._args) {
    super(..._args);

    function f() {
      return supr("bad");
    }
  }
};
```

```js
class c extends s:
  constructor() ->
    f() -> super("bad")    
```
```js
class c extends s {
  constructor() {
    function f() {
      return super("bad");
    }
  }
};
```
It looks like the automatic `super` insertion is traversing into nested functions and deciding not to insert super calls when it finds one in a nested function. I think that's not right; the traversal shouldn't be dipping into nested scopes.

**Comment by rattrayalex** [comment]
Good catch, agreed

**Comment by rattrayalex** [comment]
Actually, looks like those examples are syntax errors anyway; chrome throws with `Uncaught SyntaxError: 'super' keyword unexpected here` and babel throws with `'super' outside of function or class`. 

Closing unless there's another example you can find...

**Comment by wcjohnson** [comment]
It's trivial to work around that syntax error just by nesting another `class`:
```js
class c extends s:
  constructor() ->
    class d extends t:
      constructor() ->
        supr("bad")
    
class d extends t:
  constructor() ->
    class e extends u:
      constructor() ->
        super("bad")
```

https://wcjohnson.github.io/lscdiag/?v=1&s=eMKcwo3CkE1qAzEMwoXCr2LCtEpgCgMDwoV4UXLCgl4gE8KCIyvDhcKtw4ceLMKZBgbDn8K9dkrDklXChmrCo8K_J8Oxw7gWwrjCuMKrw6REDHrCgcOTZMOmwpbDt8O7wonDhFgjwqZ1w7g5w6woRGfDuxrCg3nDrcK_dwNjw7gSw5DCkjLClW5NwrEAw4fCnMKQWsOlGUEDesODwqxQw5FVKFhWwqzDhzQGwqUwBsKuw79QYsOabMOVw4vDm8OvwrTDjm96w7vDkMKLwr5vwp7Dn8K0w6A8wqfDjQhnY0fDmMOeFy0_e8K4bsKAHsO6w7x_A8O0w6cAKsKnw6waBjHDp0rDu8OQd8O9wrEDJk8oZMOfwqPCrcKMQsO2wr7DscKMw6HDoj5uw6zDozQ7T8KpcsOzRsKIBUrCqQLDr2rCpQ8rw6DCj8Klw7wAX1jCml8#

**Comment by rattrayalex** [comment]
Nice, thanks. Will fix.

**Comment by rattrayalex** [comment]
fixed in https://github.com/lightscript/babel-plugin-lightscript/commit/cbfa79528c57c89b8531c2e92e33e6edf2a99d16
