### ISSUE TITLE
[preset] Class property decorators

### ISSUE THREAD

**Issue by wcjohnson** [lightscript/lightscript#41]
## Problem
Using the preset with default settings,
```js
class T:
  @dec
  x = 1
```
compiles to:
```js
"use strict";

function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }

var T = function T() {
  _classCallCheck(this, T);
};
```
This is just an empty class (not correct)

## Cause
`transform-decorators-legacy` must appear BEFORE `transform-class-properties` in the plugin chain.

**Comment by wcjohnson** [comment]
Fixed above.

**Comment by rattrayalex** [comment]
Thanks! Fixed in https://github.com/lightscript/babel-preset-lightscript/commit/3cb8e138230fcfe572837020474420baca42ddb2
