### ISSUE TITLE
suggestion: pipe operator instead of tilde

### ISSUE THREAD

**Issue by tomByrer** [lightscript/lightscript#42]
```javascript
// the following invocations are equivalent:

let result = exclaim(capitalize(doubleSay("hello")));
result //=> "Hello, hello!"

// es-proposal
let result = "hello"
  |> doubleSay
  |> capitalize
  |> exclaim;

// is this corect LS?
now result = doublesay("hello")~capitalize()~exclaim()

// I suggest es-proposal in addition to these versions:
let result = "hello"|>doubleSay|>capitalize|>exclaim
let result = "hello" |> doubleSay |> capitalize |> exclaim // I like the best!
```
https://github.com/gilbert/es-pipeline-operator#esnext-proposal-the-pipeline-operator
(based on prior art from 7 other languages)

Perhaps my eyes are getting old & I need to make `font-size:20px`, but it is hard to tell `~` from `-` & even `=` if I'm tired.  Worse that you require it right next to the function name; my brain jumps to "negative function".
I like the idea of still using a `>` as part of the function realm; seems to harmonize with fat & skinny arrows.

Thanks for your consideration.

**Comment by wcjohnson** [comment]
Some thoughts:

- Note that `~` actually has different semantics from `|>`:
```js
a~b(c)
// compiles to
b(a,c)
```
whereas
```js
a |> b(c)
// compiles to
b(c)(a)
```
Thus the pipe operator can't directly replace the `~` operator.

- I like the pipe operator and would definitely consider implementing it behind a `pipeOperator` compiler flag in my branch. However, I've found the `~` to be very useful in practice and as such I don't think I would remove it. The pipe operator could coexist with it.

- What is the status of that proposal for JS? Is it in the TC39 process anywhere?

**Comment by rattrayalex** [comment]
Thanks for the input @tomByrer ! I hadn't thought about that before – I wonder if it'd continue to be hard to see after using lsc for a bit. 

As @wcjohnson mentioned, the semantics are a bit different – and I personally much prefer the `~` semantics. 

That said, I'm considering `~>` instead of `~` for the glyph, primarily because `~>` could theoretically be merged into JS (I'm considering submitting a TC39 proposal. 

Curious for thoughts?

**Comment by rattrayalex** [comment]
Oh, and to answer your question, 

```jsx
// is this corect LS?
now result = doublesay("hello")~capitalize()~exclaim()
```
Yes, that its correct LightScript (abbreviated LSC, not LS :smile: ), though you could also do:
```jsx
// is this corect LS?
now result = "hello"~doublesay()~capitalize()~exclaim()
```
(though I prefer your original construction)

Note that with the bangcall proposal implemented in @wcjohnson 's branch of the language, it could also be written
```jsx
now result = doublesay("hello")
  ~capitalize!
  ~exclaim!
// or, with ~>
now result = doublesay("hello")
  ~>capitalize!
  ~>exclaim!
```
which is probably what I would hope would become idiomatic.

EDIT:
The reasoning is largely that this is more explicit. The `|>` semantics are a little more magical: a variable is actually being called as a function, whaa?
LSC's syntax is also a bit more chaining-friendly, sticking with idiomatic JS convention. eg, you can seamlessly blend method and fns:

```jsx
foo()
  ~bar()
  .map(baz)
  ~qux()
```

**Comment by haltcase** [comment]
I think I'd be ok with `~>` if it needs to change to distinguish it from a hyphen.

The pipe operator proposal isn't getting anywhere - Brian Terlson's the champion and he's still working on it but there's quite a bit of opposition partly because of the kind of magic that @rattrayalex mentioned. I'm a big fan of the logical flow it enables ( like the tilde call here does ) but I'm not sure it'll end up in the language. Maybe something like `~>` ( or its semantics ) would have a better shot, since it integrates so well with a huge chunk of the ecosystem, like lodash's functions and most others that take the most important argument first.

**Comment by wcjohnson** [comment]
As a "character count matters" guy, I'm not thrilled with `~>` -- but if the tradeoff is a legitimate chance of getting it on the JS standards track, I'd be okay with that. (Chances are I would personally keep support for both syntaxes, though.)

**Comment by tomByrer** [comment]
> Note that ~ actually has different semantics from |>:

Ah, `~` is something like a curry, while |> is more like function chaining?  (at least that is how I can place it in my mind, perhaps not in reality)

`~>` is a bit more readable to me.  Well, I don't really 'read' anymore; I only scan.
Newbies can pick up `~>` may have something to do with functions better than plain tilde.  Also, it will stand out more via code highlighting & [ligatures](https://github.com/tonsky/FiraCode).

> The |> semantics are a little more magical: a variable is actually being called as a function, whaa?

I can see that; instead of reading forward always, one has to read backwards to see if that 'variable' is a function with a pipe operator before it.  Perhaps:
`let result = "hello" |> doubleSay() |> capitalize() |> exclaim()` ?
but maybe ice cream cone operator would be  best? ;)
`let result = "hello"|> doubleSay()> capitalize()> exclaim()`

**Comment by rattrayalex** [comment]
yes, the fact that (idiomatically) there aren't spaces around the `~` or `~>` is much to its advantage in my opinion. 

`()>` would be a grammar ambiguity with greater-than, unfortunately. 

I'm pretty set on `~` or `~>` as a fallback, though I'm certainly open to new ideas for a js-compatible alternative. I'm going to close this for now, but feel free to keep suggesting other alternatives!

**Comment by tomByrer** [comment]
FYI, function chaining is already available via [lodash `flow`](https://lodash.com/docs/4.17.4#flow).

**Comment by rattrayalex** [comment]
Yes, this can be achieved in several ways today. There are several advantages to this syntactic sugar over tools like `lodash.flow` or `rambda.pipe`. 

For one, the ability to pass args-after-the-first is quite nice in practice, and doesn't require an awkward curry, partial, or binding dance. Eg; 

```js
bob~giveMoneyTo(alice)
array~flatMap(fn).map(fn2)~lastIndexOf('foo', 3)
```

It also requires fewer characters (`flow` requires an array, plus you have to actually write `_.flow`) and you can mix-and-match methods and functions, which I don't believe is possible with the other tools.

**Comment by haltcase** [comment]
> For one, the ability to pass args-after-the-first is quite nice in practice, and doesn't require an awkward curry, partial, or binding dance.

This along with the fact that it's compiled away are the two most primary reasons `~` is better than a runtime method like `flow`.

**Comment by tomByrer** [comment]
"pass args-after-the-first" is a good point; cheers.

I do like your basic API, though lately I prefer to have only 1 action per line (I scan down better than across) & I like the sqiggly arrow better.

BTW, my lodash mention wasn't to convince you to change your mind; it was more of a 'note to self' & others who find the thread later.
