### ISSUE TITLE
[plugin] bangCall throws error in if expression

### ISSUE THREAD

**Issue by plexigras** [lightscript/lightscript#44]
```js
xor = (x, y) => (x or y) and not (x and y)
if x ~xor! y: z
```
trows `unknown: Paren-free test expressions must be followed by braces or a colon. (3:15)`

```js
if x ~xor(y): z
if (x ~xor! y): z
```
both work

[here](https://wcjohnson.github.io/lscdiag/?v=1&s=eMOafVBNT8ODMAzDvSvDgScmw7VQw7EhwqDDksOQEGfDuAPDncKEwrzDlMOtMsK5ScKVOlLCu8Kqw7x2wpzCiSvDpMKSZ8Onw6XCvWcvw5DCuklSwqQRwqoFwr56HMOywr3Dm8O1JMOYwqBgwq7DrMO5wqnCvMKbexdKPcO3wo8PwpfDqcOlw7IcbTxDJTHDkVrDvMOHWGAMKVrDisKIRwsVTCHCmsKtwrnCnQozb8OMw7ZVwpHDkcKOYsO0wo3DsUFyI8ODecKzw7d7w69aM8KZb8O9c2PDpsOKXEDDncKSw4tiwoJHw41cwpdFeShgJCYrw5R8woZGwp18YsOOwqnCgm9dd8KdIMO0woNjworDqsOOKDQKFMOQEsO-w45dw4PDgGjDqRTCuMKhw7gWwrtRX8KPw6jCu3dkBhUPwoPCuMOgwq8LGlDChMKiw79AwrEnw6dVGxpqMcKxw6RcA8Knw45lXn1YV8Ktw5nCqcKRwqrDv8K9HcOlw70Aw5LDiH_Cog#) the example in lscdiag

**Comment by wcjohnson** [comment]
@plexigras Can you move this issue over to https://github.com/wcjohnson/lightscript/issues -- bang calls aren't in the mainline branch yet.

**Comment by plexigras** [comment]
moved to https://github.com/wcjohnson/lightscript/issues/22
