### ISSUE TITLE
[eslint] no-undef with for-key/val, for-idx/elem

### ISSUE THREAD

**Issue by wcjohnson** [lightscript/lightscript#8]
Leaving this here because issue tracker on the other repo is currently locked or something.

The new `for..in` loops create no-undef warnings everywhere to the point where they basically have to be disabled in eslintrc. Not surprising on accont of the new AST nodes.

I think we should transform these into regular for loops inside the `lightscript-eslint` AST monkey patch. I will try this locally and see how it works out. Thoughts?

**Comment by rattrayalex** [comment]
Yeah, basically. Minor amounts of dark magic seem necessary. For example, `for-in-object` that has both key and val should probably transform to `for-in` where the `left` is an VariableDeclaration with an ObjectPattern with `{_k, _v}` equivalent output, if that makes sense

**Comment by wcjohnson** [comment]
I expect #12 plus a few changes to the linter will fix this as well.

**Comment by rattrayalex** [comment]
https://github.com/lightscript/lightscript-eslint/commit/4c43050cdb57dfd5088485e09068ff0d3d2526a3 

It's not very good, but it's a start. 

Have you tried updating the linter?

**Comment by rattrayalex** [comment]
Closing as I believe this to have been fixed.

**Comment by wcjohnson** [comment]
Not sure I'd consider this one fixed yet. For-in loops that use both `key` and `val` simultaneously are still triggering false no-undef errors.

**Comment by rattrayalex** [comment]
Ah, right. Thanks. I'll update the title to match.

**Comment by rattrayalex** [comment]
Fixed in https://github.com/lightscript/lightscript-eslint/commit/c7c13eee425f048ea89b83f21f72a5975757f42d

**Comment by rattrayalex** [comment]
(available in lightscript-eslint 0.5.1)
